Python 3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.

======================== RESTART: D:/scope of python.py ========================
4

======================== RESTART: D:/scope of python.py ========================
4
y:  10
x:  4
inside the function y:  10

======================== RESTART: D:/scope of python.py ========================
4
y:  10
x:  4
inside the function y:  10
y:  10
x:  5
inside the function y:  7

======================== RESTART: D:/scope of python.py ========================
4
y:  10
x:  4
inside the function y:  10
y:  10
x:  5
inside the function y:  7
y:  20
Traceback (most recent call last):
  File "D:/scope of python.py", line 39, in <module>
    inner( )
  File "D:/scope of python.py", line 35, in inner
    y=y+1
UnboundLocalError: local variable 'y' referenced before assignment

======================== RESTART: D:/scope of python.py ========================
4
y:  10
x:  4
inside the function y:  10
y:  10
x:  5
inside the function y:  7
y:  20
Traceback (most recent call last):
  File "D:/scope of python.py", line 39, in <module>
    inner( )
  File "D:/scope of python.py", line 35, in inner
    y=y+1
UnboundLocalError: local variable 'y' referenced before assignment

======================== RESTART: D:/scope of python.py ========================
4
y:  10
x:  4
inside the function y:  10
y:  10
x:  5
inside the function y:  7
y:  20
Traceback (most recent call last):
  File "D:/scope of python.py", line 39, in <module>
    inner( )
  File "D:/scope of python.py", line 35, in inner
    y=y+1
UnboundLocalError: local variable 'y' referenced before assignment

======================== RESTART: D:/scope of python.py ========================
4
y:  10
x:  4
inside the function y:  10
y:  10
x:  5
inside the function y:  7
y:  20
Traceback (most recent call last):
  File "D:/scope of python.py", line 39, in <module>
    inner( )
  File "D:/scope of python.py", line 35, in inner
    y=y+1
UnboundLocalError: local variable 'y' referenced before assignment

======================== RESTART: D:/scope of python.py ========================
4
y:  10
x:  4
inside the function y:  10
y:  10
x:  5
inside the function y:  7
y:  20
Traceback (most recent call last):
  File "D:/scope of python.py", line 39, in <module>
    inner( )
  File "D:/scope of python.py", line 35, in inner
    y=y+1
UnboundLocalError: local variable 'y' referenced before assignment

======================== RESTART: D:/scope of python.py ========================
4
y:  10
x:  4
inside the function y:  10
y:  10
x:  5
inside the function y:  7
y:  20
Traceback (most recent call last):
  File "D:/scope of python.py", line 39, in <module>
    inner( )
  File "D:/scope of python.py", line 35, in inner
    y=y+1
UnboundLocalError: local variable 'y' referenced before assignment
>>> 
======================== RESTART: D:/scope of python.py ========================
4
y:  10
x:  4
inside the function y:  10
y:  10
x:  5
inside the function y:  7
y:  20
Traceback (most recent call last):
  File "D:/scope of python.py", line 39, in <module>
    inner( )
  File "D:/scope of python.py", line 35, in inner
    y=y+1
UnboundLocalError: local variable 'y' referenced before assignment
>>> 
==================== RESTART: D:/enclosed scope in python.py ===================
x:  4
inside the function z:  10
z:  10
>>> 
==================== RESTART: D:/enclosed scope in python.py ===================
x:  4
inside the function z:  10
z:  10
x:  4
inside the function z:  16
z:  16
>>> 
==================== RESTART: D:/enclosed scope in python.py ===================
x:  4
inside the function z:  10
z:  10
x:  4
inside the function z:  16
z:  16
hi
